### ISSUE TITLE
Strange Internal Error

### ISSUE THREAD

**Issue by ra4king** [TricksterGuy/Brandonsim#4]
java.util.ConcurrentModificationException
        at com.cburch.logisim.util.SmallSet$ArrayIterator.next(SmallSet.java:32)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
        at java.util.HashSet.<init>(HashSet.java:119)
        at com.cburch.logisim.circuit.CircuitState.processDirtyPoints(CircuitState.java:364)
        at com.cburch.logisim.circuit.Propagator.clearDirtyPoints(Propagator.java:375)
        at com.cburch.logisim.circuit.Propagator.stepInternal(Propagator.java:259)
        at com.cburch.logisim.circuit.Propagator.propagate(Propagator.java:187)
        at com.cburch.logisim.circuit.Simulator$PropagationManager.run(Simulator.java:114)

**Comment by ra4king** [comment]
After investigation, this exception happened due to multiple threads modifying the same Set (dirtyPoints), not due to an add within a for-each loop. In other words...... I ain't investigating further :-1:
